version: "3.8"

services:
  app:
    build: .
    container_name: entain
    env_file:
      - .env/dev
    environment:
      ENTAIN_DB_HOST: "postgresql"  
    ports:
      - "8080:8080"
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    image: postgres
    container_name: postgresql
    env_file:
      - .env/dev
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=$ENTAIN_DB_USER
      - POSTGRES_PASSWORD=$ENTAIN_DB_PASSWORD
      - POSTGRES_DB=$ENTAIN_DB_NAME
      - POSTGRES_HOST=$ENTAIN_DB_PORT
    command: -p 5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $ENTAIN_DB_NAME -d $ENTAIN_DB_NAME'"]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata: