version: "3.8"

services:
  app:
    build: .
    container_name: entain
    env_file:
      - .env/dev
    environment:
      ENTAIN_DB_HOST: "postgresql"  
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    restart: on-failure  
  postgresql:
    image: postgres
    container_name: postgresql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=entain
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=entain
      - POSTGRES_HOST=5432
    command: -p 5432
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata: